### ISSUE TITLE
速度の計測

### ISSUE THREAD

**Issue by ragi256** [narisada/git_practice#2]
random_calc.pyとrandom_calc_sample.pyそれぞれの速度を計算したいので，
処理全体にかかった時間を計測できるように書き換えてください．
できあがったら，1から1000までのランダムな値が10,000,000行書かれたファイルで速度を比較してみてください．

**Comment by narisada** [comment]
変更しました.
random_calc.pyの計測時間は14.129913(s)
random_calc_sample.pyの計測時間は9.855411１(s)
でした.
